### ISSUE TITLE
Any URLs I try to use say "refused to connect"

### ISSUE THREAD

**Issue by pdawg17** [AgP42/MMM-SmartWebDisplay#13]
Any ideas? I've tried YouTube videos and other websites. On my browser when I access the MM it shows an empty box that says the URL "refused to connect". On my mirror, nothing shows up at all. Thank you!

UPDATE: Ok I can now see YouTube videos correctly so I know it works. But I'm trying to display weather data from my weather station which is displayed on a website. Is that possible with this module? Is still says "refused to connect" for that type of site.

UPDATE 2: Ok the problem must be the specific website I want. Do certain types of sites "not work"? This is what I'm trying to use:

https://www.wunderground.com/dashboard/pws/KCASANMA271

**Comment by AgP42** [comment]
Yes some websites doesn't work, it is written on the documentation with a link to test your website.
