### ISSUE TITLE
YouTube playlist

### ISSUE THREAD

**Issue by reallykeene** [AgP42/MMM-SmartWebDisplay#15]
When I update my YouTube playlist the modules continues to play the first video, but the next videos are unavailable. I also noticed the embedded URL did not change. How do I fix this?

**Comment by AgP42** [comment]
Hello,

The embedded url must be the one of the playlist, so it is normal that it doesn't change when you change the playlist content through YouTube.

I don't understand where is the bug. Did you read the documentation of the module ?

Bye,
AgP

**Comment by reallykeene** [comment]
Do the playlists need to be public?

**Comment by AgP42** [comment]
Your MagicMirror need to have access to the playlist, so or public or you must login your MagicMirror to YouTube to have the correct cookies
