### ISSUE TITLE
Unable to Access local .pdf/.txt files on Raspberry Pi

### ISSUE THREAD

**Issue by pandeyprakhar00** [AgP42/MMM-SmartWebDisplay#16]
Hi,

I tried opening .txt & .pdf files by typing the following commands in url section :
**file:///home/pi/Desktop/File.pdf**

Assuming that i have the file placed on Desktop named "File.pdf"
In the debug window i got the following message :
**GET http://0.0.0.0:8080/home/pi/Desktop/File.pdf 404 (Not Found)**

Please correct me if i am making any mistake.
Thanks in advance ! :-)

**Comment by AgP42** [comment]
Hello, 

I never try something like that, but I will be surprised that it can work !

Try to put your pdf file into google doc (or another web service) and use that link into the MagicMirror, probably better chances !

More globally my module is using iFrames, so you can also ask google how to display pdf files within an iFrame, it can gives you some advices. 

Let me know !

Bye, 
AgP

**Comment by pandeyprakhar00** [comment]
I tried using google drive, However got this message :

**Refused to display 'https://drive.google.com/file/d/1TxK9d4JswiPOuCFZ1XL0e3MKY6CJNaSj/view?usp=drive_open' in a frame because it set 'X-Frame-Options' to 'sameorigin'.**

I will google some other options and let you know.

**Comment by pandeyprakhar00** [comment]
Tried various options but none of them seems to work for me..

**Comment by AgP42** [comment]
Ok then sorry, it is probably not compatible with pdf !

**Comment by pandeyprakhar00** [comment]
I got a work around for pdf's, first we need to upload the PDF to 

Yumpu.com

And then copy the embed link.. it's works for me.. :-)

**Comment by AgP42** [comment]
great, good to know ! ;-)
