### ISSUE TITLE
Not an issue, but need to be upgraded to display all website

### ISSUE THREAD

**Issue by bugsounet** [AgP42/MMM-SmartWebDisplay#17]
hi,

i suggest you upgrade your module to display **ALL** website and link
`iframe` can't open every link
for exemple you can't open `google` website
with upgrade:

![Screenshot_20200418_145121](https://user-images.githubusercontent.com/30669209/79638303-20413800-8185-11ea-95e6-f7c0d135bcdd.png)

regards, 
[@bugsounet](https://github.com/bugsounet)

**Comment by AgP42** [comment]
Sure, please send me your Pull Request to do so !

This module is based on iFrames, it is written on the documentation, so yes it is limited to websites supporting this technology...
