### ISSUE TITLE
the modules does not automatically refresh

### ISSUE THREAD

**Issue by Pengree** [AgP42/MMM-SmartWebDisplay#3]
@AgP42 
First of all, thank you for providing us this fantastic module on Magic Mirror!

I installed and reconfigured the module MMM-SmartWebDisplay. I found that all functions work fine, except for the _**autoRefresh**_ feature. My config is as followings:
```
		{
			module: 'MMM-SmartWebDisplay',
			classes: 'default',
			position: 'middle_center',
			config: {
				
				logDebug: false,
				height:"1200px", 
				width:"100%",
				updateInterval: 0.5,
				NextURLInterval: 0.5,
				displayStateInfos: false,	
				displayLastUpdate: false, 
				displayLastUpdateFormat: 'ddd - HH:mm:ss',
				url: ["http://localhost:8123/lovelace/default_view"],
				scrolling: "no"
			}
		},
```

Even if I add the config parameter _**autoRefresh: true**_, it does not work yet. I don't know where the problem is.
Could you or someone give me some suggestions? Thanks in advance.

**Comment by AgP42** [comment]
hello, 

sorry for my late answer, I didn't had time so far to check your issue, but it is on my to do list !
I am a bit busy those weeks, I will try to test it this week end, 

bye

**Comment by pvancald** [comment]
Hi,
I'm having the same issue.
Here is my configuration:

{
                        module: 'MMM-SmartWebDisplay',
                        position: 'top_center', // This can be any of the regions.
                        config: {
                                // See 'Configuration options' for more information.
                                url: ["https://gadgets.buienradar.nl/gadget/zoommap/?lat=50.53596&lng=5.56775&overname=2&zoom=11&naam=esneux&size=2&voor=1"], //url to display
                                height: '256px',
                                width: '256px',
                                updateInterval: 5,
                                NextURLInterval: 0.5,
                                displayLastUpdate: false,
                                displayStateInfos: true,
                                scrolling: "no",
                                autoRefresh: true
                                }
                },


I had to use MMM-iFrame-Ping to have the refresh working...

**Comment by AgP42** [comment]
> 
> 
> @AgP42
> First of all, thank you for providing us this fantastic module on Magic Mirror!
> 
> I installed and reconfigured the module MMM-SmartWebDisplay. I found that all functions work fine, except for the _**autoRefresh**_ feature. My config is as followings:
> 
> ```
> 		{
> 			module: 'MMM-SmartWebDisplay',
> 			classes: 'default',
> 			position: 'middle_center',
> 			config: {
> 				
> 				logDebug: false,
> 				height:"1200px", 
> 				width:"100%",
> 				updateInterval: 0.5,
> 				NextURLInterval: 0.5,
> 				displayStateInfos: false,	
> 				displayLastUpdate: false, 
> 				displayLastUpdateFormat: 'ddd - HH:mm:ss',
> 				url: ["http://localhost:8123/lovelace/default_view"],
> 				scrolling: "no"
> 			}
> 		},
> ```
> 
> Even if I add the config parameter _**autoRefresh: true**_, it does not work yet. I don't know where the problem is.
> Could you or someone give me some suggestions? Thanks in advance.

Hello, 

first sorry that I said in April "next week-end" and I didn't do it...

if your problem is still present, here is an answer : 
the parameter "autoRefresh" is not impremented on this module, so of course cannot work. 
As you have only 1 url, you should use only "updateInterval: 0.5," and remove "NextURLInterval: 0.5,"

Also do you use and remote command to manage the module ? The notification "SWD_URL" can impact the update of the urls. 

Please let me know if your problem is still present !

**Comment by AgP42** [comment]
> 
> 
> Hi,
> I'm having the same issue.
> Here is my configuration:
> 
> {
> module: 'MMM-SmartWebDisplay',
> position: 'top_center', // This can be any of the regions.
> config: {
> // See 'Configuration options' for more information.
> url: ["https://gadgets.buienradar.nl/gadget/zoommap/?lat=50.53596&lng=5.56775&overname=2&zoom=11&naam=esneux&size=2&voor=1"], //url to display
> height: '256px',
> width: '256px',
> updateInterval: 5,
> NextURLInterval: 0.5,
> displayLastUpdate: false,
> displayStateInfos: true,
> scrolling: "no",
> autoRefresh: true
> }
> },
> 
> I had to use MMM-iFrame-Ping to have the refresh working...

Hi, 
I don't know why you try to use the "autoRefresh: true", this parameter is not implementer on this module. 
As you have only 1 url, you should use only the "updateInterval" and not "NextURLInterval". 

I also checked your url, it can be display on an iFrame, but as I see it the refresh is already managed by the target url itself, so why to you want an extra update interval ?
Or maybe I didn't understand correctly that url as I don't speak Netherlander !

**Comment by AgP42** [comment]
Hi, 

more than a month without answer, I consider it close, let me know if you still need help !

AgP
