### ISSUE TITLE
zoom inside iframe

### ISSUE THREAD

**Issue by chassain** [AgP42/MMM-SmartWebDisplay#7]
hello,

thanks for your module.
i would like to have a zoom inside the iframe (1000px;500px) to display all web's parameters.
a zoom inside css reduce only windows but not inside.
thanks

**Comment by AgP42** [comment]
Hello, 

what did you try on the CSS to have this behavior ? 

Did you set the CSS in this part : 
```
iframe{

border:0 ; 
/*transform: scale(0.5) ; */
/*margin-bottom: 200px;*/

}
```

Here is a link with some clue how to manage a zoom by CSS on an iFrame : [https://stackoverflow.com/questions/166160/how-can-i-scale-the-content-of-an-iframe](https://stackoverflow.com/questions/166160/how-can-i-scale-the-content-of-an-iframe)

Please let us know when solved !

AgP

**Comment by chassain** [comment]
hello,

thanks but no change with your configuration..

**Comment by chassain** [comment]
`	{
		module: 'MMM-SmartWebDisplay',
		position: 'middle_center',	// This can be any of the regions.
		config: {
			// See 'Configuration options' for more information.
			logDebug: false, //set to true to get detailed debug logs. To see them : "Ctrl+Shift+i"
			height:"1600px", //hauteur du cadre en pixel ou %
			width:"1000px", //largeur
               		updateInterval: 0, //in min. Set it to 0 for no refresh (for videos)
                	NextURLInterval: 0.5, //in min, set it to 0 not to have automatic URL change. If only 1 URL given, it will be updated
                	displayStateInfos: false,	//to display if the module is on autoloop, or stop. 
                	displayLastUpdate: false, //to display the last update of the URL
			displayLastUpdateFormat: 'ddd - HH:mm:ss', //format of the date and time to display
                	url: ["http://magicmirror.builders/"], //source of the URL to be displayed
                	scrolling: "no" // allow scrolling or not. html 4 only
			}
	},
`

**Comment by AgP42** [comment]
Hello, 

this is the conf file, did you update the .css file ? 
You will find it on "MagicMirror/modules/MMM-SmartWebDisplay"

Then into the .css file, the part to be updated is 
```
iframe{

border:0 ; 
/*transform: scale(0.5) ; */
/*margin-bottom: 200px;*/

}
```

**Comment by chassain** [comment]
hello,

yes i have this in the .css file. The frame is always the same when i transform scale..

**Comment by chassain** [comment]
Sorry..i m so bad..i should delete /* :)

**Comment by chassain** [comment]
i have to find good parameters to see all  magicmirror builder's page in the frame

**Comment by AgP42** [comment]
Hello, 

yes exactly, you have to find the good parameter to fit your need

**Comment by dwburger** [comment]
I can place the module in the top_right region at the size I want using config.js:

height:"200px", //hauteur du cadre en pixel ou %
width:"400px", //largeur

However, I'm not able to reduce the size of the URL webpage so I can see more of it.  The relevant .css is as follows:

.mainWrapper{
margin-bottom: 2px;
transform: scale(1.0) ;
}

iframe{
border:0 ; 
transform: scale(0.9) ;
margin-bottom: 2px;
}

I'm not understanding how to reduce the size of the URL webpage so more of it fits inside the region I've set.  Whenever I try to reduce the size of the webpage so I can see more of it, the entire region gets smaller.  Can someone clarify this for me?  Thanks!
